---
- hosts: all
  tasks:
    ######################
    # Initialisation roles
    ######################
    - name: init rôle Ansible
      command: ansible-galaxy init flask.packer

    - name: init gunicorn
      command: ansible-galaxy init gunicorn.packer

    - name: init Supervisor
      command: ansible-galaxy init supervisor.packer

    - name: init Nginx
      command: ansible-galaxy init nginx.packer

    - name: init sqlite
      command: ansible-galaxy init sqlite.packer

    ######################
    # Copie des fichiers
    ######################
    - name: Remove files flask
      file: path=/home/aksl/Workspace/Vagrant/flask.packer/tasks/main.yml
            state=absent

    - name: Remove files gunicorn
      file: path=/home/aksl/Workspace/Vagrant/gunicorn.packer/tasks/main.yml
            state=absent

    - name: Remove files supervisor
      file: path=/home/aksl/Workspace/Vagrant/supervisor.packer/tasks/main.yml
            state=absent

    - name: Remove files nginx
      file: path=/home/aksl/Workspace/Vagrant/supervisor.packer/tasks/main.yml
            state=absent
    ###################
    # Nginx
    ##################


    - name: Remove default site config
      file: path=/etc/nginx/sites-enabled/default
              state=absent

    ###################
    # Supervisor
    ###################
    
    ###################
    # Sqlite
    ##################


    ###################
    # Virtual env
    ##################
    - name: Install virtual env
      pip: name=virtualenv

    ###################
    # Gunicorn
    ##################
    - name: Install gunicorn
      pip: name=gunicorn

    ###################
    # Flask
    ##################
    - name: Install flask
      pip: name=flask
